# Change these first
owner: matchID-project # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: www.matchid.io
    url: https://www.matchid.io
    expectedStatusCodes: [200]
  - name: deces.matchid.io website
    url: https://deces.matchid.io
    expectedStatusCodes: [200]
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: décès
  - name: deces.matchid.io search API
    url: https://deces.matchid.io/deces/api/v1/search?q=pompidou
    expectedStatusCodes: [200]
    __dangerous__body_down_if_text_missing: Pompidou
    maxResponseTime: 2000
  - name: dev-deces.matchid.io website
    url: https://dev-deces.matchid.io
    expectedStatusCodes: [200]
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: décès
  - name: dev-deces.matchid.io search API
    url: https://dev-deces.matchid.io/deces/api/v1/search?q=pompidou
    expectedStatusCodes: [200]
    __dangerous__body_down_if_text_missing: Pompidou
    maxResponseTime: 2000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  faviconSvg: https://matchid.io/assets/images/favicon.svg
  # baseUrl: /your-repo-name
  cname: uptime.matchid.io
  logoUrl: https://matchid.io/assets/images/favicon.svg
  name: Statut matchID
  introTitle: "**matchID**"
  introMessage: Cette page présente le statut des produits matchID, à l'aide de l'outil [Uptime.js.org](https://github.com/upptime/upptime).
  navbar:
    - title: Statut
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees: # Users to assign downtime issues (optional)
  - rhanka
